name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # Установка Node.js версии 18.x
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            # Установка зависимостей
            - name: Install dependencies
              run: npm ci

            # Сборка проекта
            - name: Build project
              run: npx vite build

            # Архивирование результатов сборки
            - name: Archive artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist
